name: Deno PR check

on:
  workflow_call:

  pull_request:
    branches: ['master']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4.1.6

      - name: Setup Deno
        uses: denoland/setup-deno@1.4.0
        with:
          deno-version: v1.x
      
      # 处理 deno compile 静态资源不打包
      # shared/template 目录文件，转换为 js 文件
      - name: 处理 deno compile 静态资源不打包
        run: deno task pack

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
