name: Deno PR check

on:
  workflow_call:

  pull_request:
    branches: ['master']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4.1.3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
