# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Publish to release

on:
  push:
    branches: ["master", "main"]
    paths:
      - deno.json

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml

  release:
    runs-on: ubuntu-latest
    needs: check
    # 发布时需要提供写入权限
    permissions:
      contents: write
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - name: Setup repo
        uses: actions/checkout@v5.0.0

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v1.x

      # 执行编译命令
      - name: Run compile mac
        run: deno task build:mac
      - name: Run compile mac M
        run: deno task build:mac-m
      - name: Run compile windows
        run: deno task build:win
      - name: Run compile linux
        run: deno task build:linux

      # 创建版本文件
      - name: 创建版本文件
        id: create_version_file
        run: |
          deno task version
          echo "TAG=$(cat ./release/version)" >> $GITHUB_ENV

      # 生成变更日志
      - name: Generate Changelog
        id: changelog
        run: |
          # 获取上一个tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            # 如果没有上一个tag，获取所有提交记录
            CHANGELOG=$(git log --pretty=format:"* %s" --no-merges)
          else
            # 获取从上一个tag到现在的提交记录
            CHANGELOG=$(git log --pretty=format:"* %s" --no-merges ${PREV_TAG}..HEAD)
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # 发布到 Release
      - name: Publish to Release
        id: publish_release
        uses: softprops/action-gh-release@v2
        env:
          TAG: ${{ env.TAG }}
          CHANGELOG: ${{ env.CHANGELOG }}
        with:
          files: ./release/!(version)
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          body: |
            ## What's Changed
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      # 发布到 JSR
      - name: Publish to JSR
        id: publish_jsr
        run: deno publish
