name: Publish Package to npmjs

on:
  push:
    branches: ['master']
    paths:
      - src/npm/package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x

      # 使用 dnt(https​://deno.land/x/dnt​@0.38.0/mod.ts) 打包
      - name: 构建成 npm 包
        run: deno task build:npm

      # Setup .npmrc file to publish to npm
      - name: 发布到 npmjs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          cd npm_dist

          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
